USE flightsDB;

INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Aberdeen', 'APG', 'Phillips AAF', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Aberdeen', 'ABR', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Abilene', 'DYS', 'Dyess AFB', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Abilene', 'ABI', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Abingdon', 'VJI', 'Virginia Highlands', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Ada', 'ADT', 'Ada', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Adak Island', 'ADK', 'Adak Island Ns', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Adrian', 'ADG', 'Lenawee County', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Afton', 'AFO', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Aiken', 'AIK', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Ainsworth', 'ANW', 'Ainsworth', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Akhiok', 'AKK', 'Akhiok SPB', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Akiachak', 'KKI', 'Spb', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Akiak', 'AKI', 'Akiak', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Akron CO', 'AKO', 'Colorado Plains Regional Airport', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Akron/Canton OH', 'CAK', 'Akron/canton Regional', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Akron/Canton', 'AKC', 'Fulton International', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Akutan', 'KQA', 'Akutan', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alakanuk', 'AUK', 'Alakanuk', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alameda', 'NGZ', 'NAS', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alamogordo', 'HMN', 'Holloman AFB', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alamogordo', 'ALM', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alamosa', 'ALS', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Albany', 'NAB', 'Albany NAS', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Albany', 'ABY', 'Dougherty County', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Albany', 'ALB', 'Albany International', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Albany', 'CVO', 'Albany', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Albert Lea', 'AEL', 'Albert Lea', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Albuquerque', 'ABQ', 'Albuquerque International', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Aleknagik', 'WKK', 'Aleknagik', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Aleneva', 'AED', 'Aleneva', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alexander City AL', 'ALX', 'Thomas C Russell Fld', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alexandria LA', 'AEX', 'Alexandria International', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alexandria', 'ESF', 'Esler Field', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alexandria', 'AXN', 'Alexandria', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alexandria Bay', 'AXB', 'Alexandria Bay', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Algona', 'AXG', 'Algona', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alice', 'ALI', 'International', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Aliceville AL', 'AIV', 'George Downer', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alitak', 'ALZ', 'Alitak SPB', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Allakaket', 'AET', 'Allakaket', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alliance', 'AIA', 'Alliance', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alma', 'AMN', 'Gratiot Community', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alpena', 'APN', 'Alpena County Regional', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alpine', 'ALE', 'Alpine', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alton', 'ALN', 'Alton', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Altus', 'LTS', 'Altus AFB', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Altus', 'AXS', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Alyeska', 'AQY', 'Alyeska', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Amarillo ', 'AMA', 'Rick Husband Amarillo International', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Amarillo', 'TDW', 'Tradewind', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Ambler', 'ABL', 'Ambler', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Amchitka', 'AHT', 'Amchitka', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Amery', 'AHH', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Ames', 'AMW', 'Ames', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Amityville', 'AYZ', 'Zahns', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Amook', 'AOS', 'Amook', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anacortes', 'OTS', 'Anacortes', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anacostia', 'NDV', 'USN Heliport', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anaheim', 'ANA', 'Orange County Steel Salvage Heliport', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anaktuvuk', 'AKP', 'Anaktuvuk', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anchorage', 'EDF', 'Elmendorf Afb', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anchorage', 'ANC', 'Ted Stevens Anchorage International Airport', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anchorage', 'MRI', 'Merrill Field', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anderson', 'AID', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anderson', 'AND', 'Anderson', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Andrews', 'ADR', 'Andrews', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Angel Fire', 'AXX', 'Angel Fire', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Angola', 'ANQ', 'Tri-State Steuben Cty', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Angoon', 'AGN', 'Angoon', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anguilla', 'RFK', 'Rollang Field', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Aniak', 'ANI', 'Aniak', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anita Bay', 'AIB', 'Anita Bay', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Ann Arbor MI', 'ARB', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Annapolis', 'ANP', 'Lee', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Annette Island', 'ANN', 'Annette Island', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anniston AL', 'ANB', 'Anniston Metropolitan', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anniston', 'QAW', 'Ft Mcclellan Bus Trml', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anniston', 'RLI', 'Reilly AHP', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anthony', 'ANY', 'Anthony', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Antlers', 'ATE', 'Antlers', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Anvik', 'ANV', 'Anvik', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Apalachicola', 'AAF', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Apple Valley', 'APV', 'Apple Valley', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Appleton', 'ATW', 'Outagamie County', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Arapahoe', 'AHF', 'Municipal', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Arcata', 'ACV', 'Arcata', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Arctic Village', 'ARC', 'Arctic Village', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Ardmore', 'AHD', 'Downtown', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Ardmore', 'ADM', 'Ardmore Municipal Arpt', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Arlington Heights', 'JLH', 'US Army Heliport', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Artesia', 'ATS', 'Artesia', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Neptune', 'ARX', 'Asbury Park', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Ashland', 'ASX', 'Ashland', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Ashley', 'ASY', 'Ashley', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Aspen', 'ASE', 'Aspen', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Astoria', 'AST', 'Astoria', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Athens', 'AHN', 'Athens', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Athens', 'ATO', 'Ohio University', 'United States', 'US');
INSERT INTO airports (city, code, name, country, country_abbr) VALUES ('Athens', 'MMI', 'McMinn County', 'United States', 'US');